spring:
  application:
    name: calendar

  datasource:
    url: jdbc:postgresql://localhost:5439/calendar_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true